version: '3.8'
services:
    argo-nezha:
        image: fscarmen/argo-nezha
        container_name: nezha_dashboard
        restart: always
        environment:
           - GH_USER=Camprx
           - GH_EMAIL=campusbyscv@mailo.com
           - GH_PAT=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
           - GH_REPO=nezha0518_backup
           - GH_CLIENTID=39128093b7e393864495
           - GH_CLIENTSECRET=803639e638086fc2f7079fcc50eea29d370db731
           - ARGO_JSON='{"AccountTag":"a7d928fe22732b7c2e62f653c9658fc3","TunnelSecret":"QV1XDrLsHMU2T4k+u6iqw7jN5qiPZc+RHZ0Kcxz4Imc=","TunnelID":"2f6c7cf8-1c32-456e-a219-2ef9bcbc2bae"}'
           - WEB_DOMAIN=nezha.theshop.gq
           - DATA_DOMAIN=data.theshop.gq
           - SSH_DOMAIN=ssh.theshop.gq
           - SSH_PASSWORD=sshnezha